name: Sonar Scan
on: 
  push:
    branches:
      - sonar
jobs:
  sonarqube:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.7
    - name: Copy Dependencies
      run: gradle katalonCopyDependencies
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Sonar scan
      run:  gradle sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.verbose=true