name: Sonar Scan
on: 
  push:
    branches:
      - sonar
jobs:
  sonarqube:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: guillonapa/action-maven-cli/jdk8@master
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run:  gradle katalonPluginPackage