name: Sonar Scan
on: 
  push:
    branches:
      - sonar
jobs:
  sonarqube:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.7
    - name: Copy Dependencies
      run: gradle katalonCopyDependencies
    - name: Copy Libs
      run: |
        docker create --name tmp katalonstudio/katalon
        docker cp tmp:/opt/katalonstudio/plugins/. ./Libs
        docker cp tmp:/opt/katalonstudio/configuration/resources/lib/. ./Libs
        docker rm tmp
    - name: Plugin Package
      run: gradle katalonPluginPackage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
