name: Sonar Scan
on: 
  push:
    branches:
      - sonar
jobs:
  sonarqube:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: katalonstudio/katalon
    steps:
    - uses: actions/checkout@v3
    - name: Copy Dependencies
      run: gradle katalonCopyDependencies
    - name: Copy Libs
      run: |
        mkdir -p ./Libs
        cp -r /opt/katalonstudio/plugins/. /opt/katalonstudio/configuration/resources/lib/. ./Libs
    - name: Plugin Package
      run: gradle katalonPluginPackage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
